---
title: "Capstone"
author: "Jullian Schrup"
date: '2022-06-20'
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(tidytext)
library(caret)
library(fastDummies)
library(randomForest)
library(ggplot2)
library(rpart)
library(rpart.plot)
library(xgboost)
library(MASS)
library(janitor)
library(psych)
library(corrplot)
library(scales)
library(ggthemes)
library(mboost)
library(bst)
library(h2o)
library(reshape2)
library(ShapleyValue)
library(kableExtra)
library(car)
library(readxl)
library(blogdown)


DMM_2022_Data_BST_Used <- read.csv("C:/Users/julli/Downloads/DMM 2022 - Data - BST - Used (10).csv")
DMM_2022_Data_FST_Used <- read.csv("C:/Users/julli/Downloads/DMM 2022 - Data - FST - Used.csv")
HiddenData <- read.csv("C:/Users/julli/Downloads/DMM_CSV_2Weeks.csv")
HiddenFST <- read.csv("C:/Users/julli/Downloads/HiddenFST.csv")
BST <- clean_names(DMM_2022_Data_BST_Used)
BST <- dplyr::select(BST, -c(entry_page_home_page, entry_page_includes_size, entry_page_includes_tire_type, entry_page_includes_vehicles, entry_page_includes_tire_brands, tdp_entry, csc_entry))

FST <- clean_names(DMM_2022_Data_FST_Used)
FST <- dplyr::select(FST, -c(entry_page_home_page, entry_page_includes_size, entry_page_includes_tire_type, entry_page_includes_vehicles, entry_page_includes_tire_brands, tdp_entry, csc_entry))


```
# STEP 1: PCA - FACTOR ANALYSIS" FST
```{r}

DMM <- FST %>% filter(promo == 0) %>% dplyr::select(-c(brand,region,week,revenue))

## FACTOR

DMM_1 <- prcomp(x = DMM)
screeplot(DMM_1, type = "lines") ## We want to cutoff the screeplot at 4 factors

prc <- bind_cols(dplyr::select(FST %>% filter(promo == 0),revenue),as.data.frame(DMM_1$x))

# Correlation with Revenue
correlationmatrix <- cor(x = prc, y = prc$revenue) 
correlationmatrix

filteredcorrelations <- as.data.frame(apply(correlationmatrix, 2, function(x) ifelse (abs(x) >=0.10, round(x,3), "-")))
filteredcorrelations

melted_cormat <- melt(correlationmatrix)

ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  + 
  scale_fill_gradient2(low = "#075AFF",
                       mid = "#FFFFCC",
                       high = "#FF0000") +
  geom_tile(color = "black") +
  geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
  coord_fixed()


# Finding most correlated PCA - for FST, it's Component 2.
biplot(DMM_1, choices = c(1,2))


print(ncol(DMM_1))
DMM_1$rotation
DMM_1$rotation[,2] %>% round(2)
```
# STEP 2 FST PCA PREDICTION
```{r}
set.seed(123)
prc_index <- createDataPartition(prc$revenue, p = 0.70, list = FALSE)
train <- prc[ prc_index, ]
test <- prc[-prc_index, ]
tunegrid <- expand.grid(.mtry=1:50)


prcfit <- train(revenue ~ .,
             data = train, 
             method = "rf",
             metric = "RMSE",
             trControl = trainControl(method = "boot"),
             tuneGrid = tunegrid)

prcfit$results

summary(prcfit$results)
  plot(varImp(prcfit))


#### Forecast & MAPE

forecast_test <- data.frame(actual=test, predicted=predict(prcfit,test))
  
    print(forecast_test)
    
  
RMSE(forecast_test$actual.revenue, forecast_test$predicted) 
MAPE <- mean(abs((forecast_test$actual.revenue-forecast_test$predicted)/forecast_test$actual.revenue)) * 100
    MAPE


summary(test)

forecast_test <- data.frame(actual=test, predicted=predict(prcfit,test))

forecast_test %>% dplyr::select(c(actual.revenue,predicted)) %>% 
  ggplot(aes(x = as.numeric(row.names(forecast_test)))) +
  theme_fivethirtyeight(base_size = 12, base_family = "sans")+
  geom_point(aes(y = actual.revenue), color = "blue") + 
  geom_point(aes(y = predicted), color = 'red') + 
  geom_line(aes(y = predicted), color = 'red')+ 
  geom_line(aes(y = actual.revenue), color = 'blue') +
    labs(title = "Actual Revenue (Blue) vs. Predicted Revenue (Red)")+ 
    expand_limits(x = 0, y = 8000000)+ 
    scale_y_continuous(labels = scales::dollar_format())+
    scale_x_continuous(labels = number_format(accuracy = 1))
  
    print(forecast_test)
    
  RMSE(forecast_test$actual.revenue, forecast_test$predicted) 
  MAPE <- mean(abs((forecast_test$actual.revenue-forecast_test$predicted)/forecast_test$actual.revenue)) * 100
    MAPE


```